default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: "localhost"
  port: 3000
  database: loi_nga
  username: root

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
